### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by heyprotoman** [creativetimofficial/ct-black-dashboard-pro-react#1]
Macbook pro, chrome 71, npm 6.4.0, node 11.1.0. 

<img width="1048" alt="screen shot 2019-01-21 at 3 16 53 pm" src="https://user-images.githubusercontent.com/17154838/51501797-9b544c80-1d90-11e9-90b3-d329c75ef456.png">

**Comment by einazare** [comment]
Hello there @heyprotoman ,

Thank you for your interest in working with our product and sorry for this late response, Github did not notify me about this issue.
Did you do any changes to our product?

Best,
Manu
