### ISSUE TITLE
spinning animations

### ISSUE THREAD

**Issue by tafelito** [creativetimofficial/ct-black-dashboard-pro-react#10]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version (not sure)
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Hi, I emailed you a few days ago, not sure if you received my email. I wanted to know if it was possible to add the spinner that is already in reactstrap to the theme? I tried adding them but I guess I’m missing some css

# Current Behavior

Spinning is not working

## Context

* Device: any
* Operating System: any
* Browser and Version: any

**Comment by einazare** [comment]
Hello there, @tafelito ,

Thank you for your interest in working with our products.
Please, next time you open an issue on one of our repositories, use our ISSUES_TEMPLATE accordingly. Right now you haven't given me any steps to reproduce your issue.

It seems that the version of Reactstrap that comes with our product does not have Spinner on it.
So, to get it, you need to run in your terminal: `npm i -E reactstrap@8.0.0`.
And then, create an scss file, import it inside your index.js file and add the following code to it:
```
.spinner-border {
    display: inline-block;
    width: 2rem;
    height: 2rem;
    vertical-align: text-bottom;
    border: 0.25em solid currentColor;
    border-right-color: transparent;
    border-radius: 50%;
    -webkit-animation: spinner-border .75s linear infinite;
    animation: spinner-border .75s linear infinite;
}

@keyframes spinner-border {
  100% {
    transform: rotate(360deg);
  }
}
```

That will do the trick.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
* https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
* https://www.udemy.com/how-to-use-react-with-firebase-and-redux/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by tafelito** [comment]
@EINazare that worked, thanks! how would you add the sizes and the types?

**Comment by einazare** [comment]
Hello again, @tafelito ,

Not really sure, since the https://reactstrap.github.io/ website is down at the moment.

Best,
Manu
