### ISSUE TITLE
Broken Select component style in InputGroupAddon

### ISSUE THREAD

**Issue by tafelito** [creativetimofficial/ct-black-dashboard-pro-react#11]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version (not sure)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

I wanted to add a select as an InputGroupAddon but the styling gets messed up. I was able to make it look reasonable, but the selected value of the select shows an elipsis because it has no space to show. Any ideas how to fix this? 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: desktop
* Operating System: macOS
* Browser and Version: Chrome or Safari

I looked at the issue #6 but that didn't work for the Select component. I did manage to get it to look fine adding these styles 

```
.input-group .form-group {
  .react-select__control {
    border-color: rgba($black, 0.5);
    border-radius: 0px 4px 4px 0px;
    .react-select__value-container--has-value {
      padding: 2px 10px;
      .react-select__single-value {
        color: $black;
      }
    }
  }
}
```

**Comment by einazare** [comment]
Hello there, @tafelito ,

Thank you for sharing your solution with us.
We'll make these changes in our next update.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
* https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
* https://www.udemy.com/how-to-use-react-with-firebase-and-redux/


If you've liked what you saw, help me with a comment, like, share or subscribe.
