### ISSUE TITLE
[Bug] Deprecated dependencies, babel-loader version conflict.

### ISSUE THREAD

**Issue by AndresSweeneyRios** [creativetimofficial/ct-black-dashboard-pro-react#13]
### Version
1.0.0
### Reproduction link
N/A (the project is unmodified)
### Operating System
Windows 10
### Device
Custom AMD desktop, 64bit
### Browser & Version
N/A
### Steps to reproduce
1. npm i
2. npm run start
### What is expected?
The script starts.
### What is actually happening?
```
npm WARN deprecated memoize-one@4.1.0: New custom equality api does not play well with all equality helpers. Please use v                                                                                  5.x
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to ac                                                                                  tual version of core-js@2.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated core-js@2.6.4: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN prefer global node-gyp@3.8.0 should be installed with -g
```

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.0.4"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  D:\node_modules\babel-loader (version: 8.0.5)
```

---

### Additional comments
Fresh installation, tried to start with yarn and npm, tried manually cleaning and using the `install:clean` script. I think these problems have the same cause and the same solution (to update the dependencies), so I've created a single issue.

**Comment by einazare** [comment]
Hello there, @Andr3wRiv3rs ,

Thank you for your interest in working with our products.
I've just made a clean install && start on both windows and mac machine, and everything worked fine.
Please check that you have the latest versions of node.js and npm.
If you do not have the latest versions, please upgrade to them (we usually use the LTS version of node.js, but it should work with the Current as well).
I've made the following video (NOTE! The video will be available 7 days): https://we.tl/t-t0GCJEB0N2
If after updating node.js and npm to the latest versions, you still have this issue, I will have to ask you to provide us with a video similar to the video that I have made. Also, in your video, I will require you to run in your cmd/bash/etc the following commands:
```
node -v
npm -v
```

Thank you, and I will wait for your response.

Manu

**Comment by AndresSweeneyRios** [comment]
I don't think you're understanding me, @EINazare. Version 1.0.0, the only available download, has severely outdated dependencies, and is requesting an OLDER version of babel-loader (requesting 8.0.4 even though 8.0.5 installs). I am on LTS.

**Comment by einazare** [comment]
Hello again, @Andr3wRiv3rs ,

The product should work properly even though the dependencies are outdated.
I am not sure if you believe me, but there are still people that are using react versions 0.x.y, versions that are at least 3 years old.

Please provide the requested video.

Best,
Manu

**Comment by assohail** [comment]
I upgraded both Npm and Node but still giving the problem.

**Comment by einazare** [comment]
Hello there, @Aohail ,

What npm and Node versions do you have?

Best,
Manu

**Comment by kaiz97** [comment]
$ npm install
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

**Comment by kaiz97** [comment]
$ npm -v
6.11.3
