### ISSUE TITLE
[Bug] Minor display issues

### ISSUE THREAD

**Issue by giannoug** [creativetimofficial/ct-black-dashboard-pro-react#14]
### Version
1.0
### Reproduction link
https://demos.creative-tim.com/black-dashboard-pro-react/
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Version 75.0.3770.142 (Official Build) (64-bit)
### Steps to reproduce
I'm describing three different bugs below:

1. In a page with not enough content, no matter the content, the page will always have a scroll bar. This is bad experience to the user.

Example link: https://demos.creative-tim.com/black-dashboard-pro-react/#/admin/user-profile

2. When scrolling, the icon above the sidebar doesn't stay above it and scrolls with the page. It doesn't happen with Black Dashboard PRO HTML version. Check the icon above the sidebar:

WORKING -> https://demos.creative-tim.com/marketplace/black-dashboard-pro/examples/dashboard.html
NOT WORKING -> https://demos.creative-tim.com/black-dashboard-pro-react/#/admin/dashboard

3. A small sidebar appears on the bottom of the sidebar when the it is expanded.

Example (open the sidebar and look at the bottom of it): https://demos.creative-tim.com/black-dashboard-pro-react/#/admin/dashboard

### What is expected?
1. No scrolling is shown when content fits the page
2. The icon should stay on top of the menu bar
3. No scrolling bar is shown
### What is actually happening?
1. Scrolling occurs
2. The icon scrolls with the content
3. You can see a scrollbar that vanishes when you click it.

---

**Comment by einazare** [comment]
Hello there, @giannoug ,

Thank you for your interest in working with our products.

> In a page with not enough content, no matter the content, the page will always have a scroll bar. This is bad experience to the user.

This is actually browser default behavior. You need to have a scroll effect, for users that modify the browser height. If we were to add for example:
```
overflow: hidden;
```
And one user would make the browser windows smaller, it would not have a scroll bar. Take a look at the following images:
<img width="1920" alt="Screen Shot 2019-08-07 at 11 42 03 AM" src="https://user-images.githubusercontent.com/26245512/62608620-d4a57180-b908-11e9-89ad-757f0d82cb57.png">
<img width="1920" alt="Screen Shot 2019-08-07 at 11 43 28 AM" src="https://user-images.githubusercontent.com/26245512/62608622-d53e0800-b908-11e9-8cf5-7689eb3a01be.png">
Hope this clarifies a bit your concern.

> When scrolling, the icon above the sidebar doesn't stay above it and scrolls with the page. It doesn't happen with Black Dashboard PRO HTML version. Check the icon above the sidebar:

I can see that the icon is staying above the Sidebar. Maybe I didn't understand your question correctly. Could you please provide some additional comments on this? Maybe some images?
<img width="1920" alt="Screen Shot 2019-08-07 at 11 48 18 AM" src="https://user-images.githubusercontent.com/26245512/62608853-601f0280-b909-11e9-9846-5b21f221d1fe.png">
<img width="1920" alt="Screen Shot 2019-08-07 at 11 48 42 AM" src="https://user-images.githubusercontent.com/26245512/62608854-60b79900-b909-11e9-84f1-5a63f83b7f8e.png">

> A small sidebar appears on the bottom of the sidebar when the it is expanded.

Go inside this file: `src/components/Sidebar/Sidebar.jsx` and change 
```
ps = new PerfectScrollbar(this.refs.sidebar);
```
to 
```
ps = new PerfectScrollbar(this.refs.sidebar, {
        suppressScrollX: true,
        suppressScrollY: false
      });
```

Will wait for your response.

Best,
Manu

**Comment by giannoug** [comment]
> This is actually browser default behavior. You need to have a scroll effect, for users that modify the browser height.

You don't need to show a scrollbar and allow the page to scroll when the content fits the page.
For example look at this page: https://demos.creative-tim.com/black-dashboard-pro-react/#/auth/login

>I can see that the icon is staying above the Sidebar. Maybe I didn't understand your question correctly. Could you please provide some additional comments on this? Maybe some images?

![mpompa](https://user-images.githubusercontent.com/509474/62610826-1801df00-b90d-11e9-8356-4b51caa857c5.png)

When you scroll, the icon leaves with the content on the React version (left). On the HTML version (right) it stays on top of the sidebar.

>Go inside this file: src/components/Sidebar/Sidebar.jsx and change

Thanks that worked!

**Comment by einazare** [comment]
Hello again, @giannoug ,

> You don't need to show a scrollbar and allow the page to scroll when the content fits the page.
For example look at this page: https://demos.creative-tim.com/black-dashboard-pro-react/#/auth/login

We are sorry about this, but we can't modify this.

> When you scroll, the icon leaves with the content on the React version (left). On the HTML version (right) it stays on top of the sidebar.

Maybe this is a bug only on windows devices. Since I am not at the office until next Monday I will not be able to test this. I will come back then with a fix.

Best,
Manu

**Comment by giannoug** [comment]
> We are sorry about this, but we can't modify this.

I was able to fix this by changing
`.footer {
    padding: 24px 30px;
}`
to
`.footer {
    padding: 24px 30px 0 30px;
}`

> Since I am not at the office until next Monday I will not be able to test this. I will come back then with a fix.

Thanks!

**Comment by einazare** [comment]
Hello again, @giannoug ,

Thank you for your patience.
I've found out why the second issue is happening.
It is because we are using perfect-scrollbar to make a nice scrollbar on Windows devices, something like the scrollbar from the MacOS. This means that the event listener for the scroll on the window selector will not get fired - the scroll is not happening on the window element on Windows devices.
Please add the following line of code inside `src/layouts/Admin/Admin.jsx`, after `if (navigator.platform.indexOf("Win") > -1) {`:
```
this.refs.mainPanel.addEventListener("ps-scroll-y", this.showNavbarButton);
```

Hope this helps.

Please leave the issue opened.

Best,
Manu
