### ISSUE TITLE
[Bug] How to set background in pages (pricing/login etc)

### ISSUE THREAD

**Issue by saumitrabg** [creativetimofficial/ct-black-dashboard-pro-react#16]
### Version
 1.0.0
### Reproduction link
http://easytoreproduce.com
### Operating System
Ubuntu 16.04
### Device
PC
### Browser & Version
Google Chrome
### Steps to reproduce
1. Add background as below
class Pricing extends React.Component {
 36   componentDidMount() {
 37     document.body.classList.toggle("pricing-page");
 38   }
 39   componentWillUnmount() {
 40     document.body.classList.toggle("pricing-page");
 41   }
 42   render() {
 43     return (
 44       <>
 45         <div className="content" style={{backgroundImage: "../../assets/img/winter_background.jpg"}}>
 46           <Container>
 47             <Row>

2. I can't see the background reflected. I tried chaging the scss file and this didn't help
### What is expected?
Background image needs to appear as I customize my app
### What is actually happening?
Still shows the black background in the pages

---

**Comment by einazare** [comment]
Hello there, @saumitrabg ,

Thank you for your interest in working with our products and complying with our rules of opening a Github issue.
This not a bug with our product actually.
You are doing it wrong.
In React, if you want to add an image you need to use the require or the import statement.
Furthermore, if you want a background image using the style property (in either html/css/react/etc), you need to add the url("path/to/image"), syntax, and not only the "path/to/image".
So this syntax is not correct:
```
style={{backgroundImage: "../../assets/img/winter_background.jpg"}}
```
The correct syntax is this one:
```
style={{backgroundImage: "url(" + require("assets/img/tania.jpg") + ")"}}
```

Hope this clears your issue.

Best,
Manu
