### ISSUE TITLE
PerfectScrollbar on Windows should have dark colors

### ISSUE THREAD

**Issue by einazare** [creativetimofficial/ct-black-dashboard-pro-react#19]
### What is your enhancement?
If you check the PerfectScrollbar for the responsive tables, you will see that on Windows devices, the tables will have some white/light-colored scrollbars.
It would be nice to make those white/light-colors to be dark.

**Comment by matholt** [comment]
Just an additional note, this is happening on a Mac OS X laptop. Works fine on the laptop, but when I show it on my external display (24") is when I start noticing it.

Thank you,
Matt

**Comment by einazare** [comment]
After careful consideration, we've decided to keep the perfect scrollbar as is.
To change the colors, you can add the following scss code:
```
*:not(.white-content){
  .ps__rail-y, .ps__rail-x {
    background-color: rgba(0,0,0, 0.3) !important;
  }
  .ps__thumb-y, .ps__thumb-x {
    background-color: $default !important;
  }
}
```

Best,
Manu
