### ISSUE TITLE
Do these react pro stylesheets work with electron.js?

### ISSUE THREAD

**Issue by dtrue** [creativetimofficial/ct-black-dashboard-pro-react#2]

**Comment by einazare** [comment]
Hello @dtrue ,

And thank you for your interest in using our product.
We haven't used electron.js in any of our products and can't really answer your question.
But I am going to tell you what we've told to a lot of our users that wanted something in our products that we haven't used, you can try our free version of this product and see if it suits your needs.
Here is a link to it: https://www.creative-tim.com/product/black-dashboard-react

Best,

**Comment by dtrue** [comment]
I have the paid version already.  So nobody has requested the use of your
guys styles in an electron app before??

Thanks,
Dan

**Comment by einazare** [comment]
Hello again, @dtrue ,

I do not recall if somebody has requested electron, if so, unfortunately, he got the same answer as you did.
Does electron not support scss files?
If so, then you can compile our scss files with the Build Tools of this product: https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/build-tools

Does this help?

Best,
Manu

**Comment by gknapp** [comment]
@dtrue If you open this in a BrowserWindow or `webview`, this would render as if you've opened in Chrome?

**Comment by dtrue** [comment]
Yeah - I've confirmed it works with electron.  Thanks for the assistance!  You can close the issue!
