### ISSUE TITLE
Windows install issue 

### ISSUE THREAD

**Issue by atikurrahman102** [creativetimofficial/ct-black-dashboard-pro-react#20]
./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0)
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found orphan CR, try removeCR option)

Any Solution ??? this is on windows 10

**Comment by einazare** [comment]
Hello there, @atikurrahman102 ,

Thank you for your interest in working with our products.
Please, next time use our issue template, otherwise, we will close your issue:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/black-dashboard-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```
When you've pressed the new issue button, were you not prompted with the above code?
To solve the issue please run the following commands:
```
npm i -E node-sass@4.13.0
npm install
npm start
```

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Team!
I have the same issue with your product after upgrading react-scripts higher then 3.0.1 version.
This issue is decribed here:
https://github.com/sass/node-sass/issues/2756
I guess, you use different line endings in your scss files.
Can you check it and fix?
Much appreciated and thanks.

**Comment by einazare** [comment]
Hello there, @DmitryTezh ,

Please do not make changes to the versions inside the package.json file.
Our product works with the versions that come.
We will make those changes in our next update, right now we do not have the time to check what breaks when changing versions inside our products. We are doing this when we make updates.

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Manu!
We look forward to this issue get fixed.  Upgrading to the latest version of react-scripts is caused to use new features like those:
v3.3.0 is a minor release that adds new features, including custom templates and support for the new optional chaining and nullish coalescing operators.
Thanks.

**Comment by einazare** [comment]
Hello there, @DmitryTezh ,

Right now we are stuck on some other projects until the end of this year (2019).
We'll start updating all of the Creative-Tim products starting with January next year (2020), after we come from our Christmas holiday, which ends after 5th of January. Thank you for your understanding.

Best,
Manu

**Comment by atikurrahman102** [comment]
loader: 'resolve-url-loader',
options: {
removeCR: true,
sourceMap: true
}

This could be a solution . Any idea where can i put them ???

**Comment by DmitryTezh** [comment]
I guess, you need to eject your react project to ajust its configuration but then you will not able to upgrade to the newest versions of react-scripts.

**Comment by einazare** [comment]
Hello there, @atikurrahman102 @DmitryTezh ,

This solution did not work?
```
npm i -E node-sass@4.13.0
npm install
npm start
```
Also, on one of our products, one of our users gave us this: https://github.com/creativetimofficial/ct-paper-kit-pro-react/issues/2#issuecomment-565728755

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Team!
Unfortunately, no. I have the last version of node-sass@4.13.0 and it doesn,t work.
Thanks.

**Comment by einazare** [comment]
Hello again, @DmitryTezh ,

I've just made a quick test, and if I run the above command on Windows and on Mac, everything works just fine.
Can you please go to https://nodejs.org/en/ and download the 12.14.0 (LTS) version?
Maybe the issue is that you do not have the LTS version of NodeJS.

Best,
Manu

**Comment by atikurrahman102** [comment]
./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0
(./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0)
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found
orphan CR, try removeCR option)


This is the error .My node version is lts the same above .

**Comment by einazare** [comment]
Hello there, @atikurrahman102 ,

I am at an impasse.
Please provide me with the following video:

- Download product
- Unzip downloaded product
- Open terminal and CD into the unzipped product
- Goto [NodeJS website](https://nodejs.org/en/), download and install the Latest (LTS version)
- Run in terminal `node -v`
- Run in terminal `npm -v`
- Run in terminal `npm i -E node-sass@4.13.0`
- Run in terminal `npm install`
- Run in terminal `npm start`
- Showcase the issue

Best,
Manu

**Comment by DmitryTezh** [comment]
> Hello again, @DmitryTezh ,
> 
> I've just made a quick test, and if I run the above command on Windows and on Mac, everything works just fine.
> Can you please go to https://nodejs.org/en/ and download the 12.14.0 (LTS) version?
> Maybe the issue is that you do not have the LTS version of NodeJS.
> 
> Best,
> Manu

Hi Team!
It is strange but amazing! Upgrading of NodeJS to 12 LTS version fixed my issue.
Thank you!

**Comment by DmitryTezh** [comment]
Unfortunately, not all is good. Command 'npm run buid' failed with the same error, whilst command 'npm run start' works fine. Very strange for me...

**Comment by DmitryTezh** [comment]
> ofg-client-web@0.1.0 build D:\Projects\offgame\ofg-client-web
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found orphan CR, try removeCR option)

**Comment by atikurrahman102** [comment]
$ node -v
v12.14.0

$ npm -v
6.13.4

+ node-sass@4.13.0
updated 1 package and audited 905906 packages in 44.984s


./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0
(./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0)
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found
orphan CR, try removeCR option)

**Comment by einazare** [comment]
I am at an impasse.
Please provide me with the following video:

Download product
Unzip downloaded product
Open terminal and CD into the unzipped product
Goto NodeJS website, download and install the Latest (LTS version)
Run in terminal node -v
Run in terminal npm -v
Run in terminal npm i -E node-sass@4.13.0
Run in terminal npm install
Run in terminal npm start
Showcase the issue
Best,
Manu

**Comment by dewhurstwill** [comment]
@EINazare Still having issues; https://youtu.be/9k-wSv-Glsg

**Comment by einazare** [comment]
Hello again, @willdewhust ,

If you copy the src/assets/img folder into src/assets/scss/black-dashboard-pro-react folder, do you still have that issue? (Note, keep the folder inside src/assets/img as well).
It's very strange the fact that I do not get any errors, everything is working as expected.

Best,
Manu

**Comment by dewhurstwill** [comment]
Hello @EINazare,

Strangely that has fixed it? It now works. :)

Thanks you

**Comment by Theeeus** [comment]
I just had the same issue and none of the solutions above worked for me. In the end I had to navigate to `node_modules/resolve-url-loader` and under `var options`  manually change removeCR from "false" to "true"
