### ISSUE TITLE
[Feature Request] when black dashboard pro react get same updates like your other themes?

### ISSUE THREAD

**Issue by buncis** [creativetimofficial/ct-black-dashboard-pro-react#22]
### What is your enhancement?
in any other of your themes you got version bugfix where it remove `.env` and change it with `jsconfig.json` black dashboard still not get that update.

and that makes me got this problem 

Failed to compile.

./src/index.js
Module not found: Can't resolve 'assets/css/nucleo-icons.css' in '/home/bc/black-dashboard-pro-react/src'

**Comment by einazare** [comment]
Hello there, @buncismamen ,

To solve the issue, you can delete the .env file and create a file named jsconfig.json with the following code inside it:
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "*": ["src/*"]
    }
  }
}
```
That should work just fine.

Let me know if you have further issues.

Best,
Manu
