### ISSUE TITLE
[Bug] Redirect to /admin/dashboard upon invalid route 

### ISSUE THREAD

**Issue by locmai0808** [creativetimofficial/ct-black-dashboard-pro-react#23]
### Version
1.0.0
### Reproduction link
https://code.lnmai.com/#/admin/dashboard
### Operating System
Windows
### Device
Desktop
### Browser & Version
Chrome 80
### Steps to reproduce
1. Go to https://code.lnmai.com/#/admin/dashboard
2. Edit the url to something like https://code.lnmai.com/#/admin/invalid and press enter
### What is expected?
Expected the app would redirect to https://code.lnmai.com/#/admin/dashboard instead of staying on https://code.lnmai.com/#/admin/invalid
### What is actually happening?
App wont redirect upon invalid route.

---
### Additional comments
According to your demo page here: https://demos.creative-tim.com/black-dashboard-pro-react/#/admin/dashboard
When you go to https://demos.creative-tim.com/black-dashboard-pro-react/#/admin/invalid, it would redirect to dashboard, without refreshing the page. 

![lDLoUTb9SN](https://user-images.githubusercontent.com/18728001/78523574-0fa4c100-7786-11ea-970a-1b6890220ba1.gif)

**Comment by einazare** [comment]
Hello there, @locmai0808 ,

I've checked our product and it works as expected.
As I can see on the links you have given me, you have made changed to our product.
Inside `src/layouts/Admin/Admin.js` inside the `<Switch>...</Switch>` component, you need to have a `Redirect`:
```
          <Switch>
            {this.getRoutes(routes)}
            <Redirect from="*" to="/admin/dashboard" />
          </Switch>
```

Also, please note this is not an issue with the product.

Best,
Manu

**Comment by locmai0808** [comment]
@EINazare Thanks! That fixed the issue.
