### ISSUE TITLE
[Bug] combo box show white on white options

### ISSUE THREAD

**Issue by buncis** [creativetimofficial/ct-black-dashboard-pro-react#26]
### Version
1.1.0
### Reproduction link
https://demos.creative-tim.com/marketplace/black-dashboard-pro/docs/1.0/components/forms.html
### Operating System
WINDOWS 7/8/8.1/10
### Device
PC/LAPTOP
### Browser & Version
Google Chrome 81.0.4044.129
### Steps to reproduce
click select or combo box it will show you white options in white background 

so it's hard to see the options except you hover it
### What is expected?
the combo box should show black font on top of white background or white font on top of black background
### What is actually happening?
click select or combo box it will show you white options in white background 

so it's hard to see the options except you hover it

the issue is os dependant because on my os x there is no this problem

combo box in windows
![93f141e9-cf78-4cb9-9ab7-7cc04b1b6bfc](https://user-images.githubusercontent.com/14258779/80880486-600c3180-8ce6-11ea-9aca-97baa2839195.jpeg)

combo box in OSX with dark theme

![dd95050c-3279-4b06-8c9f-18d153b4dcd0](https://user-images.githubusercontent.com/14258779/80880468-5edb0480-8ce6-11ea-82b0-a8dda1d9b375.jpeg)

---

**Comment by buncismamen** [comment]
![dd95050c-3279-4b06-8c9f-18d153b4dcd0](https://user-images.githubusercontent.com/14258779/80880468-5edb0480-8ce6-11ea-82b0-a8dda1d9b375.jpeg)
![93f141e9-cf78-4cb9-9ab7-7cc04b1b6bfc](https://user-images.githubusercontent.com/14258779/80880486-600c3180-8ce6-11ea-9aca-97baa2839195.jpeg)

**Comment by buncis** [comment]
I think the solution is using CustomizableSelect |  React Select v3.0.8 as in the documentation


how to use dropdown black using this solution?

**Comment by einazare** [comment]
Hello there, @buncismamen ,

Thank you for your interest in working with our products.

To solve the issue, please add the following css:
```
select > option {
  color: $default;
}
```

Please note that the link given, sends us on the HTML product, while this repository is for the React version.

Best,
Manu

**Comment by buncis** [comment]
here is the react version link https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/forms

I already fix this problem using react-select, now my problem is the react-select only give white on black combobox selection 

I want it to be black on white like dropdown .dropdown-black

https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/dropdowns

I've check this css `_plugin-react-select.scss`

but there is no black version of it like `_dropdown.scss`

can you help me with that?

**Comment by einazare** [comment]
Hello there, @buncismamen ,

I am sorry but I do not understand your question.

Best,
Manu

**Comment by buncis** [comment]
I solve my original problem, by using this solution

https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/customizable-select

the problem with this solution is the selection box only have black fonts on white background

<img width="364" alt="Screen Shot 2020-05-09 at 12 30 13" src="https://user-images.githubusercontent.com/14258779/81465012-dc27dd00-91f0-11ea-86bf-12c748f04695.png">

**my question is**

can you help me with the css code or css class to make it white font on black background

so the combobox have same colorscheme with dropdown black

like in here ? https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/dropdowns

<img width="240" alt="Screen Shot 2020-05-09 at 12 29 04" src="https://user-images.githubusercontent.com/14258779/81465003-c0bcd200-91f0-11ea-816e-6ba1bba26438.png">

**Comment by einazare** [comment]
Hello there, @buncismamen ,

To solve your issue, please go inside `src/assets/scss/black-dashboard-pro-react/react/plugins/_plugin-react-select.scss`.
Here, at line 24 you will see how we set the background color for the mentioned component (you can change it to `$default`, `dark` or even `black`). All the variable colors can be found here: `src/assets/scss/black-dashboard-pro-react/custom/_variables.scss`.
After that, for the colors of the items, you will find that on line 76.

Best,
Manu

**Comment by buncis** [comment]
thanks for your help manu, I also need to change line 34 and 46 for the triangle color
