### ISSUE TITLE
[Bug] Sorting table not rendering data

### ISSUE THREAD

**Issue by ntanwir** [creativetimofficial/ct-black-dashboard-pro-react#28]
### Version
1.1.0
### Reproduction link
https://jsfiddle.net/sxzeuydg/
### Operating System
windows
### Device
desktop
### Browser & Version
chrome 80
### Steps to reproduce
I have your regular table component. The Sorting component in it is not rendering data. But, when I do pass on the fetched data through a normal bootstrap table, it works.
### What is expected?
fetched data should be populated into the table 
### What is actually happening?
data not rendering.

---

**Comment by einazare** [comment]
Hello there, @ntanwir ,

Thank you for your interest in working with our products.
The JSFiddle you have given us, has errors, and cannot be run, so I cannot test your code.
I've created the following demo code, that works as expected:
```
/*!

=========================================================
* Black Dashboard PRO React - v1.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard-pro-react
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";

// reactstrap components
import { Card, CardHeader, CardBody, CardTitle, Row, Col } from "reactstrap";

// core components
import SortingTable from "components/SortingTable/SortingTable.js";

let data = [
  {
    data: [
      { text: "Dakota Rice" },
      { text: "Niger" },
      { text: "Oud-Turnhout" },
      { className: "text-center", text: "$36,738" }
    ]
  },
  {
    data: [
      { text: "Minerva Hooper" },
      { text: "Curaçao" },
      { text: "Sinaai-Waas" },
      { className: "text-center", text: "$23,789" }
    ]
  },
  {
    data: [
      { text: "Sage Rodriguez" },
      { text: "Netherlands" },
      { text: "Baileux" },
      { className: "text-center", text: "$56,142" }
    ]
  },
  {
    data: [
      { text: "Philip Chaney" },
      { text: "Korea, South" },
      { text: "Overland Park" },
      { className: "text-center", text: "$38,735" }
    ]
  },
  {
    data: [
      { text: "Doris Greene" },
      { text: "Malawi" },
      { text: "Feldkirchen in Kärnten" },
      { className: "text-center", text: "$63,542" }
    ]
  },
  {
    data: [
      { text: "Mason Porter" },
      { text: "Chile" },
      { text: "Gloucester" },
      { className: "text-center", text: "$78,615" }
    ]
  },
  {
    data: [
      { text: "Jon Porter" },
      { text: "Portugal" },
      { text: "Gloucester" },
      { className: "text-center", text: "$98,615" }
    ]
  }
]

class RegularTables extends React.Component {
  render() {
    return (
      <>
        <div className="content">
          <Row>
            <Col className="mb-5" md="12">
              <Card>
                <CardHeader>
                  <CardTitle tag="h4">Simple Table</CardTitle>
                </CardHeader>
                <CardBody>
                  <SortingTable
                    thead={[
                      { text: "Name" },
                      { text: "Country" },
                      { text: "City" },
                      { className: "text-center", text: "Salary" }
                    ]}
                    tbody={data}
                  />
                </CardBody>
              </Card>
            </Col>
          </Row>
        </div>
      </>
    );
  }
}

export default RegularTables;
```
As you will see, in the code above everything works as expected.
I can see that you are using `axios`, that which makes an **async** call to a DB.
My best guess is that the **async** call is not synchronized with the React rendering, i.e. React renders the page, and after that the **async** call finishes, but React will not re-render.
Unfortunately, since we haven't worked with `axios` as of the moment, we cannot offer support for this.
Our guidance for you, would be to check Redux and React-Redux, these two libraries could help you into rendering **async** calls.

Best,
Manu

**Comment by ntanwir** [comment]
@EINazare The code which I had shared in the `jsfiddle` is for a regular table. So, in order to check it out, you just have replace your regular table code with mine.

W.r.t the axios asysc calls: I do not think that is the issue since I also tried using a simple generic bootstrap table and the axios calls works perfectly in that case.

The example which you have shared contains static data which franky does not help in putting things into perspective. It would really help if you could use a simple `fetch()` to get that data and then interpolate it inside your jsx.

Regards,
Nauman.

**Comment by einazare** [comment]
Hello again, @ntanwir ,

I am sorry, but I do not know how to test your use case.

Best,
Manu
