### ISSUE TITLE
Routing isn´t working after production build

### ISSUE THREAD

**Issue by jobnbackpack** [creativetimofficial/ct-black-dashboard-pro-react#3]
# Hey there!
I´m trying to create a Dashboard for my website. I really love your Product but sadly i can´t upload it on my webserver because after the `npm run build` i only get a white page and none of the routes are working.

I changed nothing so far. I only wanted to create a production build. I use Google Chrome.

**Comment by einazare** [comment]
Hello there @jobnbackpack ,

Thank you for your interest in working with our product.
Please go inside package.json and delete the homepage prop.
That will do the trick.

Best,
Manu

**Comment by jobnbackpack** [comment]
Thank you for your fast answer @EINazare !

It was exactly the answer I was looking for.
