### ISSUE TITLE
[Bug] npm install doesn't complete

### ISSUE THREAD

**Issue by TranKovak** [creativetimofficial/ct-black-dashboard-pro-react#32]
### Version
1.1.0
### Reproduction link
https://jsfiddle.net/tn0dmcg2/1/#&togetherjs=r5ER3eQ3lx
### Operating System
Windows 10
### Device
pc
### Browser & Version
na
### Steps to reproduce
unzip black-dashboard-pro-react-v1.1.0.zip
go to folder with terminal
npm install
### What is expected?
no error 
### What is actually happening?
npm ERR! Unexpected end of JSON input while parsing near '...0171214":{"name":"typ'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2020-09-01T08_04_00_536Z-debug.log

and in the log file:
7421 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
7421 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
7421 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
7421 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
7422 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...0171214":{"name":"typ'
7422 verbose stack     at JSON.parse (<anonymous>)
7422 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
7422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
7422 verbose stack     at runMicrotasks (<anonymous>)
7422 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
7423 verbose cwd D:\Workspaces\Workspace-GRH\comptafi.admin\src
7424 verbose Windows_NT 10.0.18363
7425 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
7426 verbose node v12.16.1
7427 verbose npm  v6.13.4
7428 error Unexpected end of JSON input while parsing near '...0171214":{"name":"typ'
7429 verbose exit [ 1, true ]

---

**Comment by einazare** [comment]
Hello there, @TranKovak ,

Thank you for your interest in working with our products.
I am not sure I understand your jsfiddle. Could you please detail what should I do there?

I did a clean install of the product, i.e., download product, unzip, install and start, and everything worked as expected.
Can you please make sure you are using NodeJS LTS version 12.18.3?
If the issue persists, please make the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Best,
Manu

**Comment by TranKovak** [comment]
Hello
I update node to the last LTS like you asked and `npm install` work correctly now
thank you
