### ISSUE TITLE
[Bug] Component layout admin error on unmount

### ISSUE THREAD

**Issue by TranKovak** [creativetimofficial/ct-black-dashboard-pro-react#33]
### Version
1.1.0
### Operating System
Windows 10
### Device
pc
### Browser & Version
Firefox 80.0.1
### Steps to reproduce
Unzip project
npm install
npm start
once project started on the sidebar click on Page and Login or register (or something that will change from the adminn layout)
### What is expected?
Not crashing when we change layout
### What is actually happening?
When clicked that change the layout and trigger `componentWillUnmount` of `src/layouts/Admin/Admin.js`
and crash tha app with a `TypeError: document.documentElement.className.add is not a function`
```
componentWillUnmount
D:/Workspaces/Workspace-GRH/comptafi.admin/black_react/src/layouts/Admin/Admin.js:65

  62 | componentWillUnmount() {
  63 |   if (navigator.platform.indexOf("Win") > -1) {
  64 |     ps.destroy();
> 65 |     document.documentElement.className.add("perfect-scrollbar-off");
  66 | ^   document.documentElement.classList.remove("perfect-scrollbar-on");
  67 |     this.refs.mainPanel.removeEventListener(
  68 |       "ps-scroll-y",
```

---
### Solution
I commented the line 65 and 66 and it not crash but I don't know if it's the better thing to do

**Comment by einazare** [comment]
Hello there, @TranKovak ,

Here is the solution: https://github.com/creativetimofficial/ct-black-dashboard-pro-react/issues/24

Best,
Manu

**Comment by TranKovak** [comment]
Oh sorry I didn't check other tickets, will do next time before post an issue.
 thanks

**Comment by einazare** [comment]
No worries, at least you've used our issue template ❤️
