### ISSUE TITLE
How to load footer link on the right side?

### ISSUE THREAD

**Issue by ntanwir** [creativetimofficial/ct-black-dashboard-pro-react#34]
### What is your enhancement?
As of right now, when we click on the footer links, they can either open on the same page or in a new tab. I wish to open them on the right side just like other links in the sidebar.

how do I do that?

**Comment by einazare** [comment]
Hello there, @ntanwir ,

Thank you for your interest in working with our products.
At the moment we do not have a tutorial or that.
I've spoken with my superiors, and they decided not to add this feature to our product.
I'll leave your issue open for ~30 days with the tag `help wanted` and maybe someone from our community will come to your aid.

If not, we have a dedicated team for custom development here: [https://services.creative-tim.com/?ref=ct-footer](https://services.creative-tim.com/)

Best,
Manu

**Comment by 0xGREG** [comment]
You can use the NavLink component:

Example:
`<NavLink to="/auth/login" className="nav-link">
    <i className="tim-icons icon-single-02" /> Login
</NavLink>`
