### ISSUE TITLE
[Bug] Text in input field is invisible in modal!

### ISSUE THREAD

**Issue by abdulaziz-jm** [creativetimofficial/ct-black-dashboard-pro-react#37]
### Version
1.1.0
### Reproduction link
https://jsfiddle.net/dyu7p62m/1/
### Operating System
all
### Device
all
### Browser & Version
all
### Steps to reproduce
1. create a modal using dark mode and white modal (the same can happen when light mood and black modal).
2. add text field to modal.
3. start typing in the text field.

### What is expected?
The text should be black because the modal background is white.
The same problem happen when you use light mood and black modal.
### What is actually happening?
the text is white and the background is white, so the text becomes invisible.

---
### Solution
change the input text color to black when using white modal, and white color when the modal is black.

**Comment by einazare** [comment]
Hello there, @abdulaziz-jm ,

Thanks for providing a solution to this issue.

Best,
Manu

**Comment by abdulaziz-jm** [comment]
Are you planning on fixing this?

**Comment by einazare** [comment]
Hello there, @abdulaziz-jm ,

Yes.

Best,
Manu
