### ISSUE TITLE
Perfect Scroll on <Table responsive>

### ISSUE THREAD

**Issue by locmai0808** [creativetimofficial/ct-black-dashboard-pro-react#4]
I only want to render `<Table responsive>` if my get request returns data, so in my code I have the follow:

`let map = null;
    if (this.state.gotMap) {
      map = (
        <Col lg="12">
          <Card>
            <CardHeader>
              <CardTitle tag="h4">Global Sessions by Locations</CardTitle>
              <p className="card-category">All Sessions within 30 days</p>
            </CardHeader>
            <CardBody>
              <Row>
                <Col lg="6">
                  <VectorMap
                    ...
                  />
                </Col>
                <Col lg="6">
                  <Table responsive>
                    <tbody>
                      <tr>
                        <td>
                          <div className="flag">
                            <img alt="..." src={require("assets/img/US.png")} />
                          </div>
                        </td>
                        <td>USA</td>
                        <td className="text-right">2.920</td>
                        <td className="text-right">53.23%</td>
                      </tr>
                      <tr>
                        <td>
                          <div className="flag">
                            <img alt="..." src={require("assets/img/DE.png")} />
                          </div>
                        </td>
                        <td>Germany</td>
                        <td className="text-right">1.300</td>
                        <td className="text-right">20.43%</td>
                      </tr>
                      <tr>
                        <td>
                          <div className="flag">
                            <img alt="..." src={require("assets/img/AU.png")} />
                          </div>
                        </td>
                        <td>Australia</td>
                        <td className="text-right">760</td>
                        <td className="text-right">10.35%</td>
                      </tr>
                      <tr>
                        <td>
                          <div className="flag">
                            <img alt="..." src={require("assets/img/GB.png")} />
                          </div>
                        </td>
                        <td>United Kingdom</td>
                        <td className="text-right">690</td>
                        <td className="text-right">7.87%</td>
                      </tr>
                      <tr>
                        <td>
                          <div className="flag">
                            <img alt="..." src={require("assets/img/RO.png")} />
                          </div>
                        </td>
                        <td>Romania</td>
                        <td className="text-right">600</td>
                        <td className="text-right">5.94%</td>
                      </tr>
                      <tr>
                        <td>
                          <div className="flag">
                            <img alt="..." src={require("assets/img/BR.png")} />
                          </div>
                        </td>
                        <td>Brasil</td>
                        <td className="text-right">550</td>
                        <td className="text-right">4.34%</td>
                      </tr>
                    </tbody>
                  </Table>
                </Col>
              </Row>
            </CardBody>
          </Card>
        </Col>
      );
    }`

and in my return I include the "map" jsx element.

However when it renders successfully, perfect scroll isn't added to `<div class="table-responsive">`
![image](https://user-images.githubusercontent.com/18728001/53449231-382c8a00-39ce-11e9-969c-b90ee1c95158.png)
If I add "ps" to  `<div class="table-responsive ps">`, it would work 
![image](https://user-images.githubusercontent.com/18728001/53449289-572b1c00-39ce-11e9-92cc-62357f965b4d.png)

Please check below for my code:

![image](https://user-images.githubusercontent.com/18728001/53450348-d6b9ea80-39d0-11e9-87d3-7a9ceeb4d0b7.png)

What should I do to fix this? Thank you!

**Comment by einazare** [comment]
Hello there, @locmai0808 ,

Thank you for your interest in working with our product.
It seems that you have figured the solution. How can we help you?

Best,
Manu

**Comment by locmai0808** [comment]
Hello Manu, actually no I couldn't figure out how to fix this. My 'solution' was to add "ps" to `<div class="table-responsive ps">` in F12 (Developer Tools of Chrome). And that isn't really a solution then if I had to open Developer Tools to manually add "ps"

> Hello there, @locmai0808 ,
> 
> Thank you for your interest in working with our product.
> It seems that you have figured the solution. How can we help you?
> 
> Best,
> Manu

**Comment by einazare** [comment]
Hello again, @locmai0808 ,

That is what you should do. That is the fix.
Here is our live docs about perfect scrollbar: https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/perfect-scrollbar
If you navigate inside `src/layouts/Admin/Admin.jsx` (our product unaltered), between lines 30-41, you will see that we initialize perfect-scrollbar on the tables as well.

Best,
Manu
