### ISSUE TITLE
[Bug] Table React not working when we click the icon to remove

### ISSUE THREAD

**Issue by lucasbbs** [creativetimofficial/ct-black-dashboard-pro-react#40]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/black-dashboard-pro-react/?_ga=2.158935994.1409444556.1623213713-1327575007.1623213713#/admin/react-tables
### Operating System
windows 10
### Device
PC
### Browser & Version
Google Chrome
### Steps to reproduce
1. You click the icon to remove
2. Nothing happens, we do not get the component table updated
### What is expected?
It is expected that the table gets updated
### What is actually happening?
The table is not getting updated

---

**Comment by sajadevo** [comment]
**Hi @lucasbbs**

We only implement the UI not the entire functionalities, this part is working together with backend so first the data should come and then the delete functionality should happen.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
