### ISSUE TITLE
[Bug] 'Default Brand Text' appears as the view title for dynamic routes

### ISSUE THREAD

**Issue by Daleksander** [creativetimofficial/ct-black-dashboard-pro-react#42]
### Version
1.2.1
### Reproduction link
https://www.creative-tim.com/product/black-dashboard-pro-react
### Operating System
Ubuntu 20.04
### Device
Dell laptop
### Browser & Version
Version 106.0.5249.119 (Official Build) (64-bit)
### Steps to reproduce
1.Just open new black-dashboard-pro-react project.
2.Add to routes new route with dynamic path.
{
path: "/device/details/:serial",
name: "DeviceDetails",
rtlName: "لوحة القيادة",
icon: "tim-icons icon-chart-pie-36",
component: DeviceDetails,
layout: "/admin",
},
3.For component: DeviceDetails import DeviceDetails from "views/pages/Login.js"; in routes.js . But it can be also anything you like.
4.To Dashboard add new button whatever you like:
<Button color="info" href = {/admin/device/details/1234-1223-1234-1234}> Go to
### What is expected?
I would expect the view title to come out as 'DeviceDetails'
### What is actually happening?
The route works fine and all, but the view title comes out as 'Default Brand Text'

---
### Solution
I guess here is a problem with if in AdminLayout:
if ( window.location.pathname.indexOf( routes[i].layout + routes[i].path ) !== -1)
since my dynamic URL is :
/admin/device/details/1234-1223-1234-1234
and in routes is :
/admin/device/details/:serial
### Additional comments
Do you have any idea what can be wrong ?

**Comment by sajadevo** [comment]
**Hey @Daleksander**

Thanks for using our product, could you please send me the image of the place you want to change it's text this way I can assist you more in a better way.

Cheers,
Sajad

**Comment by Daleksander** [comment]
![Screenshot from 2022-12-30 14-20-05](https://user-images.githubusercontent.com/101924135/210074559-8d522a0c-db39-415c-a419-583fc9a2e9bc.png)
In the top left corner. I am on url /user/dashboard and it displays Dashboard like expected but after I click on Go to button which redirects to a dynamic url : /user/device/details/abc where abc is a dynamic variable. And then in the top left corner it should print DeviceDetails but i got Default Brand Text. 
![Screenshot from 2022-12-30 14-20-43](https://user-images.githubusercontent.com/101924135/210074873-91ad2d1d-895a-4a7e-a0d3-f567a4072a70.png)

my routes look like this :
const routes = [
  {
    path: "/dashboard",
    name: "Dashboard",
    rtlName: "لوحة القيادة",
    icon: "tim-icons icon-chart-pie-36",
    component: Dashboard,
    layout: "/user",
    onSidebar: true,
  },
  {
    path: "/device/details/:serial",
    name: "DeviceDetails",
    rtlName: "لوحة القيادة",
    icon: "tim-icons icon-chart-pie-36",
    component: DeviceDetails,
    layout: "/user",
    onSidebar: false,
  },
]

**Comment by sajadevo** [comment]
@Daleksander unfortunately it doesn't support the dynamic route but you can add it if you want and get the dynamic url you would like to have.

Cheers,
Sajad

**Comment by Daleksander** [comment]
Ill leave solution that worked for me : 
const getActiveRoute = (routes) => {
        let activeRoute = "Default brand text";
        const currentPath = window.location.pathname;

        for (let i = 0; i < routes.length; i++) {
            const { path, layout, name } = routes[i];

            if (path.includes(":")) {
                // If the route has dynamic parameters, check if the current path matches
                // the layout + path without the dynamic parameter
                const basePath = layout + path.split(":")[0];
                if (currentPath.startsWith(basePath)) {
                    return name;
                }
            } else if (layout + path === currentPath) {
                // If the route does not have dynamic parameters, check if the current
                // path matches the layout + path exactly
                return name;
            }

            if (routes[i].collapse) {
                let collapseActiveRoute = getActiveRoute(routes[i].views);
                if (collapseActiveRoute !== activeRoute) {
                    return collapseActiveRoute;
                }
            }
        }

        return activeRoute;
    };
