### ISSUE TITLE
[Bug] Arabic Page

### ISSUE THREAD

**Issue by developmentdeko** [creativetimofficial/ct-black-dashboard-pro-react#43]
### Version
1.2.3
### Reproduction link
http://localhost:3000/admin/dashboard (I dont have a link)
### Operating System
macOs
### Device
Macbook Pro
### Browser & Version
Chrome 120.0.6099.199
### Steps to reproduce
Go to the /admin/dashboard
click on the RLT Page by using the navigator on the left side of the screen
The page opens in arabic language
### What is expected?
it should show the page in english (I guess)
### What is actually happening?
the page is written in arabic and the page sctructure changes (navigator on the right side)

---

**Comment by sajadevo** [comment]
It's not the issue it's the default behavior, the RTL version is for the languages that are written from right to left like Arabic or Persian.
