### ISSUE TITLE
[Bug] Light and dark theme flipped.

### ISSUE THREAD

**Issue by mtiTayyab** [creativetimofficial/ct-black-dashboard-pro-react#44]
### Version
1.2.3
### Reproduction link
Can't provide as not in production s
### Operating System
MacOS
### Device
Macbook Air M2
### Browser & Version
Chrome Version 125.0.6422.113 (Official Build) (arm64)
### Steps to reproduce
1. NPM start the dashboard
2. Open pablo and check light is selected but the theme in the dashboard is dark. 
3. When flipped to dark the theme changes to light.
4. Horizontal navbar is stuck in dark mode. 
### What is expected?
1. When light is selected, everything should be in white the background and the horizontal navbar
2. When dark is selected, everything should be in dark.
### What is actually happening?
It is the opposite and the horizontal navbar is stuck in dark mode

---

**Comment by sajadevo** [comment]
This issue is fixed on v1.2.4
