### ISSUE TITLE
Colour hex difference between Demo, Sketch & scss code.

### ISSUE THREAD

**Issue by mze-runner** [creativetimofficial/ct-black-dashboard-pro-react#5]
Hi. 
I recently purchased Black Dashboard PRO React full the package with Sketch. 
I compared two key colours of background and card on Demo, Sketch & scss code (_variables.scss). 

And came across of inconsistency. 
** The Background colour 
1/ DEMO (get it by a colour picker). hex: #1E1E2E 
2/ Sketch Style name - Black: #1E1E24 
3/ Code $background-black: #1e1e2f !default; 
So, ALL three are different.

** Card background. 
1/ DEMO (get it by colour picker). hex: #212A44
2/ Sketch Style name - Default & Dark Blue (same hex): #27293D 
3/ Code $card-black-background: #27293d !default; 
So, p2=p3, but not as on the demo! 

Story short: 
- Sketch design looks different coz colours. 
- Own site looks different than demo coz colours.

Please, let me know if you need more input.

ps. demo link
https://demos.creative-tim.com/black-dashboard-pro-react/?_ga=2.203450066.392683377.1552819095-828673728.1542099778#/admin/dashboard

**Comment by einazare** [comment]
Hello again @mze-runner ,

```
And came across of inconsistency.
** The Background colour
1/ DEMO (get it by a colour picker). hex: #1E1E2E
2/ Sketch Style name - Black: #1E1E24
3/ Code $background-black: #1e1e2f !default;
So, ALL three are different.
```
It seems to me that the background color is the same.
Please, do not use color picker when trying to figure out a color, use our scss, or the inspector of your browser. Also, to convince you that we have the same colors, take a look at the bellow image:
<img width="1920" alt="Screen Shot 2019-03-18 at 9 37 46 AM" src="https://user-images.githubusercontent.com/26245512/54514085-d2467900-4961-11e9-94ba-50895e221583.png">

```
** Card background.
1/ DEMO (get it by colour picker). hex: #212A44
2/ Sketch Style name - Default & Dark Blue (same hex): #27293D
3/ Code $card-black-background: #27293d !default;
So, p2=p3, but not as on the demo!
```
It seems to me that the background color of the Card is the same.
Please, do not use color picker when trying to figure out a color, use our scss, or the inspector of your browser. Also, to convince you that we have the same colors, take a look at the bellow image:
<img width="1920" alt="Screen Shot 2019-03-18 at 9 34 00 AM" src="https://user-images.githubusercontent.com/26245512/54514107-e12d2b80-4961-11e9-865d-817a3de47ec0.png">


Hope this helps.

Best,
Manu

**Comment by mze-runner** [comment]
Hi Manu.

Two points.
1/ Visually it looks different, this is how I pay attention to this. (this is why I used colour picker) 
Besides, you are missing the Sketch template. Please see in the attachment. I put all together to compare...
<img width="862" alt="Screenshot 2019-03-18 at 10 49 28" src="https://user-images.githubusercontent.com/25860915/54514578-96b0ac80-496b-11e9-8a19-a230a8de2e1f.png">

To me, it is crucial Sketch use absolutely the same colour scheme as sccs.

**Comment by mze-runner** [comment]
OK, I went through everything once more following the screenshots you share. 
1/ Card colour good, you right, the colour pick does not help here, agree.
2/ Background in Sketch = 1e1e24 (check it twice), on the screenshot you stated as 1e1e2f.
I am using style Colour/Black. 
Is it right one to use for the background ?

**Comment by einazare** [comment]
Hello again, @mze-runner ,

I've checked with our designers and you are right.
There are two differences.
One on the wizard card, and one for the body background
These changes were done in the product since they looked a bit nicer.
You can go ahead inside `src/assets/scss/black-dashboard-pro-react/react/plugins/_plugin-react-bootstrap-wizard.scss` and change line 86 to:
```
    background: $card-black-background;
```
And also, line 93 to:
```
    background-color: $card-black-background !important;
```
After this, you can go inside `src/assets/scss/black-dashboard-pro-react/custom/_reboot.scss` and change 
```
body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
}
```
To:
```
body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  background-color: $background-states-black;
}
```

That way, your product will look like our sketch.
The same principle can be applied vice-versa, change the Sketch to match those two colors (for the whole background and for the wizard card).

We will discuss this with our board and decide which one will choose, but I think we'll change the Sketch since the colors from the product works a bit better.

Hope this helps.

Best,
Manu

**Comment by mze-runner** [comment]
Hi Manu, 
So, my concern is not so invalid then :).

I better wait for version update to take it 'as is' and apply it to all my assets.
PS. Yes, I agree that the colour of the product looks better rather in Sketch. My buy/not buy decision done looking at the demo.

Anyway thank you for help, look forward to updated pack.
