### ISSUE TITLE
Sidebar is not collapsed (mini) by default

### ISSUE THREAD

**Issue by ovxrfl0w** [creativetimofficial/ct-black-dashboard-pro-react#7]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The sidebar should automatically be toggled as mini sidebar

# Current Behavior

This sidebar is not collapsed (mini) by default.

# Failure Information (for bugs)

``` 
constructor(props) {
    super(props);
    this.state = {
      activeColor: "blue",
      sidebarMini: true,
      opacity: 0,
      sidebarOpened: false
    };
  }
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1: create react app
2. step 2: install the theme
3. step 3: that's all

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: All devices
* Operating System: MacOS
* Browser and Version: Chrome 73.0.3683.103 (64-bit)

**Comment by einazare** [comment]
Hello there @ovxrfl0w ,

Please go inside `public/index.html` and add `sidebar-mini` class on the body tag:
```
  <body class="sidebar-mini">
```

Best,
Manu
