### ISSUE TITLE
When refresh the page a strange layout is shown before the final render

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-black-dashboard-pro-react#8]
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 :
After successfully login to my web app , i land to the dashboard page.
I have used the mock data you provide in the dashboard (sidebar page) 
hence no ajax call is made to fetch the data for the view.

2. step 2 :
Upon login , i have set some information in my session storage and then 
i want to check that my general react component which is inside the main layout page(navbar,sidebar,routes etc..) behaves as expected.

Expected means that ,the web application from the time i click refresh and the time the page is depicted there are no "strange" pictures and other staff as you can see in my attachment.

Thank you in advance,

* Device: Laptop
* Operating System: Windows 10
* Browser and Version: Google Chrome : Version 73.0.3683.103

Please check the attachment below : 

![refreshPage](https://user-images.githubusercontent.com/48952483/56278442-e9b68480-610e-11e9-9f3a-26e147b7ae2d.png)

**Comment by einazare** [comment]
Hello there @kfouSwift ,

Thank you for your interest in working with our product.
Without seeing the changes that you've made, my best guess is that this is because you did not add our styles from src/index.js where they should be.
You need those styles to get imported before anything else, that is why we set them inside src/index.js.
Can you provide a more detailed step by step guide on what changes have you made?
I can make you a video with our product, in which I change the page from the log in one to the Dashboard one, and the styles are properly applied, but this would not help you at all.

Best,
Manu

**Comment by ghost** [comment]
Hello @EINazare  ,

I am sending you some attachments to see for yourself that , i am doing the css staff  exactly as you mentioned in your previous comment.

I have no idea what is going on and this would be a product for production in the near future, hence i would like some more help.

In addition, i have to mention that i am using many different css files because i want to combine different staff from the react material kit.Maybe this is the problem maybe not...You are the expert.

Thank you a lot,
Fouster
![cssFiles](https://user-images.githubusercontent.com/48952483/56351212-42505500-61d5-11e9-9b17-d9329b59395a.PNG)
![wholeAPP](https://user-images.githubusercontent.com/48952483/56351213-441a1880-61d5-11e9-846c-b969e84b8233.PNG)
![RenderDOM](https://user-images.githubusercontent.com/48952483/56351219-454b4580-61d5-11e9-9cea-91e1248837a3.PNG)
![MainLayout](https://user-images.githubusercontent.com/48952483/56351223-47150900-61d5-11e9-87ab-6d33ca5bf77e.PNG)

**Comment by einazare** [comment]
Hello again, @kfouSwift ,

If you use just the black-dashboard-pro-react styles, is this issue still occurring?
I am quite sure, that it is not a good idea to mix the scss from two of our products., especially the Material ones with the Bootstrap (Reactstrap or React-Bootstrap) ones.
That is why we sell the products separately.
Try the above guide, and if that does not work, I will need to see your project - can't really help by guessing the issue. For this, I will require of you to open a ticket here: https://www.creative-tim.com/contact-us, or if you have a Github repository, invite me to it. Also, I will need a thorough step by step guide on how to start your project.

Best,
Manu

**Comment by ghost** [comment]
@EINazare i will try to figure it out and rewrite a new project from the scratch using only the material dashboard pro react...If i face the same issue should i reopen this issue?

BR
